return {
    
_WINDOW_FULLSCREEN = true,
_WINDOW_WIDTH = 240,
_WINDOW_HEIGHT = 320,
_WINDOW_SCALLING_X = 3,
_WINDOW_SCALLING_Y = 3,

_GAME_SHIP_SPEED = 120,
_GAME_CATRIDGE_SIZE = 4,
_GAME_ENEMY_SLOT_SIZE = 10,
_GAME_ENEMY_SPEED = 150,
_GAME_BG_SPEED = 100,
_GAME_BULLET_SPEED = -270,
_GAME_RUNING = true,
_GAME_CONTROLLS = true,
_GAME_GOBLIN_ANIMATION_SPEED = 0.25,

}